### ISSUE TITLE
Interactivity of select menus not as (I) expected (Mac Chrome)

### ISSUE THREAD

**Issue by sgolik** [MatchbookLabs/bourbon#100]
on http://bourbon.getfeedback.com/freestyle?s=Components&ss=select%20field

Generally, I feel that we shouldn't override standard web controls unless we are accommodating all their behaviors.

Specifically...

https://cl.ly/ebeb9ef695c8/Screen%20Recording%202019-01-07%20at%2005.14%20PM.gif

1. The entire container should be clickable (currently the lower and upper parts, and the actual down-carat affordance, are not)
2. Clicking again should collapse the menu
3. Typing the first few char of an option should scroll to and highlight that option

**Comment by transitorytammy** [comment]
@sgolik I will work on fixing the first 2 issues listed here.  

I think for your 3rd bullet point we have the `bourbon-search-select-field` . https://bourbon.getfeedback.com/freestyle?s=Components&ss=search%20select%20field .   Let me know if that is not the case.  Thanks.
